import { type GetStaticProps, type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import { client } from '@/libs/client'
import { type Blog } from '@/types/blog'

interface Props {
  blog: Blog[]
}

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({
    endpoint: 'blogs',
  })

  return {
    props: {
      blog: data.contents,
    },
  }
}
const Home: NextPage<Props> = ({ blog }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {blog?.map((b: Blog) => (
          <li key={b.id}>
            <Link href={`/blog/${b.id}`}>{b.title}</Link>
          </li>
        ))}
      </main>
    </>
  )
}

export default Home
