import { type GetStaticProps, type NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { ENDPOINTS, PER_PAGE } from '@/common/settings'
import Pagination from '@/components/Pagination'
import BlogCard from '@/components/blogCard/BlogCard'
import { client } from '@/libs/client'
import { type Blog } from '@/types/blog'

interface Props {
  blog: Blog[]
  totalCount: number
}

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({
    endpoint: ENDPOINTS.blogs,
    queries: {
      offset: 0,
      limit: PER_PAGE,
    },
  })

  return {
    props: {
      blog: data.contents,
      totalCount: data.totalCount,
    },
  }
}
const Home: NextPage<Props> = ({ blog, totalCount }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {blog.length > 0 && (
          <ul>
            {blog?.map((b: Blog) => (
              <BlogCard key={b.id} blog={b} />
            ))}
          </ul>
        )}
        <Pagination totalCount={totalCount} />
      </main>
    </>
  )
}

export default Home
